#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ "${SITES_ENV_READY:-}" != "1" ]]; then
  exec "${script_dir}/sites-env.sh" -- "$0" "$@"
fi

worker="${SITES_PROJECT_ROOT}/dist/server/index.js"
hosting="${SITES_PROJECT_ROOT}/dist/.openai/hosting.json"

[[ -f "${worker}" ]] || {
  echo "Missing production server artifact: dist/server/index.js" >&2
  exit 66
}

# Render runs Central as a normal Node/Vinext application. The packaged
# OpenAI Sites manifest is only required by the Cloudflare/Sites deployment
# path; it is not generated by a Node platform build and must not make the
# Render build fail.
if [[ "${RENDER:-}" == "true" || -n "${RENDER_SERVICE_ID:-}" ]]; then
  node --input-type=module - "${worker}" <<'NODE'
import { pathToFileURL } from "node:url";

// With `node - script`, argv[1] is the literal `-`; the first user argument
// (the worker path) is argv[2]. Using argv[1] produces file://-/ on Linux.
const workerPath = process.argv[2];
const workerUrl = pathToFileURL(workerPath);
workerUrl.searchParams.set("render-validation", `${process.pid}-${Date.now()}`);
const worker = await import(workerUrl.href);
if (!worker || typeof worker.fetch !== "function") {
  throw new Error("dist/server/index.js must have an ESM default export with fetch(request, env, ctx)");
}
NODE
  echo "Validated Render production artifact: ESM Worker default.fetch is present."
  exit 0
fi

[[ -f "${hosting}" ]] || {
  echo "Missing packaged Sites manifest: dist/.openai/hosting.json" >&2
  exit 66
}

node --input-type=module - "${worker}" "${hosting}" <<'NODE'
import { readFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";

const [workerPath, hostingPath] = process.argv.slice(2);
JSON.parse(await readFile(hostingPath, "utf8"));

const workerUrl = pathToFileURL(workerPath);
workerUrl.searchParams.set("sites-validation", `${process.pid}-${Date.now()}`);
const worker = await import(workerUrl.href);
if (!worker.default || typeof worker.default.fetch !== "function") {
  throw new Error("dist/server/index.js must have an ESM default export with fetch(request, env, ctx)");
}
NODE

echo "Validated Sites artifact: ESM Worker default.fetch and hosting manifest are present."
